name: Solar System Workflow


on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

env:
  MONGO_URI: ${{ secrets.MONGO_URI }}
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}



jobs:
  unit-testing:
    name: Unit Testing
    strategy:
      matrix:
        nodejs_version: [18, 19, 20]
        operating_system: [ubuntu-latest, macos-latest]
        exclude:
        - nodejs_version: 18
          operating_system: macos-latest
    runs-on: ${{ matrix.operating_system }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Setup Node.js Version - ${{ matrix.nodejs_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodejs_version }}
          check-latest: true 

      - name: Install Dependencies
        run: npm install


      - name: Run Unit Tests
        id: nodejs-unit-testing
        run: npm test

      - name: Archive Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Mocha-Test-Result
          path: test-results.xml
  
  
#   code-coverage:
#     name: Code Coverage
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4


#       - name: Setup Node.js 18
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18


#       - name: Install dependencies
#         run: npm install


#       - name: Check Code Coverage
#         continue-on-error: true
#         run: npm run coverage


#       - name: Archive coverage report
#         uses: actions/upload-artifact@v4
#         with:
#           name: Code-Coverage-Result
#           path: coverage
#           retention-days: 5
    

